name: pinelab_sdk
description: Unofficial Pinelabs Integration SDK for Keltron inhouse projects
version: 0.0.2
homepage: https://github.com/keltronswgmobile/pinelab_sdk

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  dart_code_metrics: ^4.11.0
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  plugin:
    platforms:
      android:
        package: org.keltron.pinelab_sdk
        pluginClass: PinelabSdkPlugin